site_name: A Sufficiently Large Serviette
site_url: https://sanguinecha.me/serviette/
theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/circle-half-full
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/circle-half-full
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - awesome-nav:
      logs:
        nav_override: warning
        root_title: warning
        root_hide: warning
        no_matches: warning

hooks:
  - hooks.py
